### ISSUE TITLE
overwriting

### ISSUE THREAD

**Issue by FebsN0** [jamesgleave/Deep-Docking-NonAutomated#20]
https://github.com/jamesgleave/Deep-Docking-NonAutomated/blob/eec92b595f8ac858183736f8d43f6ce887c7a926/phase_2-3/Extract_labels.py#L88

Hi, I think there is an error: it should be "a" of append instead of "w" of write, otherwise it overwrites the file *label* every time.
In this way, I would move the 89th line before the pooling of each sdf file, in order to put just the field names

**Comment by jyaacoub** [comment]
It has been a while since I have gone through this code but I believe this is a nonissue because the files are unique. We are only running this once for each set (train, valid, and test) so the multiprocessing works independently of each other.

I think we did this for the exact reasoning you are describing otherwise we would run into a readers-writers problem.
