### ISSUE TITLE
ML.lasso_regularizer

### ISSUE THREAD

**Issue by albertma-evotec** [jamesgleave/Deep-Docking-NonAutomated#7]
Thanks for uploading the ML module.
I am running the iteration_1/simple_job/simple_job_0.sh script that runs progressive_docking.py
Again it cannot find the lasso_regularizer file in ML

```
  File "/home/UK/ama/Development/deep-docking-v2/ML/Models.py", line 8, in <module>
    from ML.lasso_regularizer import Lasso
ModuleNotFoundError: No module named 'ML.lasso_regularizer'
```

**Comment by jyaacoub** [comment]
Hi, so sorry about that we have rerun some tests on phase_2-3 and it should be working now. 

We added the lasso_regularizer.py fille, and also added some other new files so be sure to download those as well.
Also, make sure you edit the activation_script.sh file so that it activates your conda environment.

Please let us know if you run into anymore issues!
