### ISSUE TITLE
Sampling.py in iterations>1

### ISSUE THREAD

**Issue by YairFrank** [jamesgleave/Deep-Docking-NonAutomated#9]
Hi,
In the README file it is written:

> sampling.py randomly samples the desired number of molecules for the training, validation and testing sets (again note that only during the first iteration do we generate the validation and testing sets).

But in subsequent iterations, _sampling.py_ still creates validation and test sets, is it OK?

Thank you,
Yair Frank

**Comment by fgentile89** [comment]
Hi Yair,
yes it is completely ok. Although they are always created, the real validation and test sets are just the ones from the first iteration (as those are true random samples of the library). In later iterations, the new created files are all part of the training enrichment, as they are also biased towards 'better scoring' molecules rather than being a representation of the database. We kept those names for internal technical reasons, with the goal to change it in the future.

**Comment by YairFrank** [comment]
Got it, thank you
